### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input     at JSON.parse (<anonymous>)     at onDrop (Canvas.wrapper.js:78)

### ISSUE THREAD

**Issue by quanNullable** [Fengzhen8023/react-workflow#1]
hello，dear，I get two erros when I Drag and drop  item onto the canvas.
<img width="865" alt="ERROR" src="https://user-images.githubusercontent.com/21003284/69412280-85fdd500-0d49-11ea-9c49-402a26e8d606.png">
Could you please help me? I just copyed your example codes,thank you!

**Comment by Fengzhen8023** [comment]
Very sorry to hear that and I think it's my fault.
Because I didn't update the README.md after I update the react-work-flow package.
I think you can execute the below code to install the previous version:
```shell
npm i react-work-flow@1.0.5
```
Hope to help you to resolve the error.

**Comment by quanNullable** [comment]
ok，thanks,I sloved this
